configs:
  team_name: 'Digital'
  repo_name: 'CallPrediction'
aml:
  agent_enviornment:
    initialize_environment: false
    enviornment_name: 'DIGITAL_CP_AGENT_ENV'
    environment_path: 'CallPrediction/devops/agent_env/DIGITAL_CP_AGENT_ENV.yml'
    library_requirement_path: 'CallPrediction/devops/agent_env/library_requirements.txt'
  aml_configuration:
    source_resource_group: 'maz-cac-aml-wstn-digital-rg'
    source_workspace: 'mazcacnpedigitalaml01'
    target_resource_group: 'maz-cac-dmt-prd-eda-stg-aml-rg'
    target_workspace: 'mazcacprdstgmtaml01'
  #aml_model_registration:
  #  - model:
  #      source_name: 'cp_RandomForest_v1_2022-02-23'
  #      target_name: 'test_cp_RandomForest_v1_2022-02-23'
  #      version: 2
  aml_pipelines:
    scoring_pipelines:
      - pipeline:
          python_script: 'run_pipeline.py'
          arguments: ['--pipeline_config CallPrediction/conf/pipeline/inferencing/stg/inference_pipeline_config.yaml', 
                      '--azure_config CallPrediction/conf/pipeline/inferencing/stg/stg_azure_config.json']
          python_path: 'CallPrediction/src'
          working_directory: 'CallPrediction/main_scripts/pipeline/batch_inference_pipeline'
